export const COLORS = {
  BACKGROUND: 0x121212,
  WALL: 0x333333,
  TANK_1: 0x00FF88, // Neon Green
  TANK_2: 0xFF3366, // Neon Pink
  TANK_3: 0x33CCFF, // Neon Blue
  BULLET: 0xFFFFFF,
  UI_TEXT: 0xEEEEEE,
  UI_ACCENT: 0x444444,
};

export const GAME_CONFIG = {
  MAZE_COLS: 12,
  MAZE_ROWS: 8,
  WALL_THICKNESS: 8,
  TANK_SIZE: 20,
  TANK_SPEED: 3,
  TANK_ROTATION_SPEED: 0.08,
  BULLET_SPEED: 6,
  BULLET_RADIUS: 3,
  BULLET_BOUNCES: 5,
  MAX_BULLETS: 5,
  TANK_MAX_HEALTH: 100,
  BULLET_DAMAGE: 25,
  POWERUP_SIZE: 20,
  POWERUP_SPAWN_CHANCE: 0.1, // Chance per cell to spawn a power-up
  POWERUP_DURATION: 10000, // 10 seconds
};

export enum PowerUpType {
  GATLING = 'GATLING',
  BIG_BULLET = 'BIG_BULLET',
  FAST_BULLET = 'FAST_BULLET',
}

export const POWERUP_COLORS = {
  [PowerUpType.GATLING]: 0xFFD700, // Gold
  [PowerUpType.BIG_BULLET]: 0xFF4500, // OrangeRed
  [PowerUpType.FAST_BULLET]: 0x00BFFF, // DeepSkyBlue
};
